### ISSUE TITLE
Add as collaborator

### ISSUE THREAD

**Issue by maudnals** [WICG/admin#123]
Hi,
Can I please be added as a collaborator to the following repo: https://github.com/WICG/conversion-measurement-api ?
Thanks!
Maud

**Comment by marcoscaceres** [comment]
done

**Comment by maudnals** [comment]
Hi Marcos, 
Thank you!

I'm still getting the same access error: 
"git push --set-upstream origin maudnals-tweaks
ERROR: Permission to WICG/conversion-measurement-api.git denied to maudnals.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists."

What I've done so far:
• joined the WICG
• [linked my W3C account with my GH account](https://www.w3.org/users/119092/connectedaccounts)
• (have been added as a collaborator to this repo)

What am I missing?

**Comment by sideshowbarker** [comment]
Hi @maudnals — the system shows that it sent an invite to you for read access to that repo, but indicates you’ve not responded to the invite yet

> I'm still getting the same access error:
> "git push --set-upstream origin maudnals-tweaks

Note that the access that was set up for you (pending your response to the invite) is for _read_ access to the repo, but not write access. So even after the system gets your response to the invite, you’re not going to be able to push a branch to the repo.

But just to be clear — and realizing I may likely be pointing out something you already well know: If your need is to create a pull request with some proposed changes to the spec, you can do that without having write access to the repo. You can fork the repo and push a branch to your own fork and then create a pull request with your fork+branch as the source, right?

**Comment by maudnals** [comment]
Hi @sideshowbarker, 
Re:fork: my mistake, I thought requesting for access would give me write rights. Yes, forking sounds like a more appropriate workflow here.
Thank you!
(+Accepted the invite)
